### ISSUE TITLE
Can't replicate results in Bayes Factor page

### ISSUE THREAD

**Issue by flimao** [fonnesbeck/fonnesbeck.github.io#1]
Hi,

The page in question is this: [Calculating Bayes factors with PyMC](http://stronginference.com/bayes-factors-pymc.html)

I ran the [model in it](https://github.com/pymc-devs/pymc/wiki/BayesFactor), using:

``` python
>>> map_ = MAP(M_m)
>>> M = MCMC(M_m)
>>> M.sample(500000, burn=250000)
```

 but I keep getting probabilities of the Poisson model being True like these:

``` python
>>> true_model.stats()['mean']
0.56470799999999999
```

The traces look like these:

![image](https://cloud.githubusercontent.com/assets/5827775/6028070/ca56d6a8-abcd-11e4-88e6-b42a50bb68ad.png)

![image](https://cloud.githubusercontent.com/assets/5827775/6028074/d0e57970-abcd-11e4-9d28-325f313e22b3.png)

![image](https://cloud.githubusercontent.com/assets/5827775/6028076/d8c7eaa6-abcd-11e4-9991-f6e938277758.png)

Changing the burn-in, or thinning the posterior sample, doesn't change the outcome. 

I speculated that maybe including the `deterministic` variable `p` in the model was making the sampler's job harder (because it's correlated with `mu`), but removing it from the model specification didn't change the outcome either.

I'm not sure what's going wrong here. Can you help me, please? I'm using version 2.3.4 of PyMC, running it in PYthon 3.4.1 x64.

Cheers!

**Comment by fonnesbeck** [comment]
Thanks for letting me know. I will have a look at this.

**Comment by fonnesbeck** [comment]
Seems to be an issue with the `Categorical` likelihood. If you replace it with a Bernoulli:

```
true_model = Bernoulli('true_model', p=pi[1], value=1)
```

It produces the expected result. Will investigate.

**Comment by flimao** [comment]
Replacing `Categorical` with `Bernoulli` indeed solved the problem. If, however, there were more than two competing models, then we'd be forced to daisy-chain `Bernoulli` variables, which is convoluted at best.

I tried using `Multinomial` with `n = 1`, but got the same buggy result.

**Comment by fonnesbeck** [comment]
You can't calculate Bayes factors for more than two models, so that's not going to be an issue in this application.

**Comment by fonnesbeck** [comment]
The problem turns out to be with the default sampler for the Categorical distribution. By default, it uses the `DiscreteMetropolis` sampler, which for only 2 categories performs poorly. Changing this manually to the `BinaryMetropolis` fixes the issue (this is what the Bernoulli uses).

```
M.use_step_method(BinaryMetropolis, true_model)
```

**Comment by fonnesbeck** [comment]
I'm going to close this in favor of pymc-devs/pymc#676 where I will push a fix.

**Comment by flimao** [comment]
OK. I'll try this solution when I get home.

BTW, which sampler do you recommend for three or more categories? I'm having a similar issue with a different model, using three categories. The three models are similar, yet result in vastly different posteriors.

**Comment by fonnesbeck** [comment]
Sorry for the late reply. When there are 3+ categories, the DiscreteMetropolis will be suitable. But again, the Bayes factor becomes less relevant when there is more than one comparison.
